---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pudim
  labels:
    k8s-app: pudim
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: pudim
  template:
    metadata:
      labels:
        k8s-app: pudim
        name: pudim
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - image: msfidelis/pudim:v0
          name: pudim
          ports:
            - name: http
              containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: pudim
spec:
  type: ClusterIP
  selector:
    k8s-app: pudim
  ports:
    - protocol: TCP
      port: 80
      name: web

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pudim-web
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`pudim.dev.qesh.ai`)
      services:
        - name: pudim
          port: 80
      middlewares:
        - name: httpsredirect

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pudim-websecure
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`pudim.dev.qesh.ai`)
      services:
        - name: pudim
          port: 80
  tls:
    secretName: pudimdevcert